force-app/main/default/objects/Association__c/Association__c.object-meta.xml
<CustomObject>
    <label>Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Association__c/fields/Relacion__c.field-meta.xml
<CustomField>
    <fullName>Relacion__c</fullName>
    <label>Relacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buena</fullName>
            </value>
            <value>
                <fullName>Mala</fullName>
            </value>
            <value>
                <fullName>Indiferente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Association__c/fields/Species1__c.field-meta.xml
<CustomField>
    <fullName>Species1__c</fullName>
    <label>Species1</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Associations</relationshipLabel>
    <relationshipName>Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Species2__c.field-meta.xml
<CustomField>
    <fullName>Species2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Associations (Species)</relationshipLabel>
    <relationshipName>Associations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssociationsService.cls
public with sharing class AssociationsService {
    public static Map<Id,Set<Id>> findPartners(Set<Id> speciesIds, String relationship) {
        List<Association__c> associations = [SELECT Species1__c, Species2__c 
                                                FROM Association__c 
                                                WHERE (Species1__c IN :speciesIds AND Relacion__c = :relationship)
                                                OR (Species2__c IN :speciesIds AND Relacion__c = :relationship)
                                                WITH USER_MODE];

        Map<Id,Set<Id>> relatedSpeciesIds = new Map<Id,Set<Id>>();
        for (Id speciesId : speciesIds) {
            relatedSpeciesIds.put(speciesId, new Set<Id>());
        }
        for(Association__c association: associations) {
            if (relatedSpeciesIds.containsKey(association.Species1__c)) {
                relatedSpeciesIds.get(association.Species1__c).add(association.Species2__c);
            }
            if (relatedSpeciesIds.containsKey(association.Species2__c)) {
                relatedSpeciesIds.get(association.Species2__c).add(association.Species1__c);
            }
        }
        return relatedSpeciesIds;
    }
}