force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Last_Fertilized__c.field-meta.xml
<CustomField>
    <fullName>Last_Fertilized__c</fullName>
    <label>Last Fertilized</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Last_Watered__c.field-meta.xml
<CustomField>
    <fullName>Last_Watered__c</fullName>
    <label>Last Watered</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Plants</relationshipLabel>
    <relationshipName>Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Species__c/Species__c.object-meta.xml
<CustomObject>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Species__c/fields/Max_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Max_Temperature__c</fullName>
    <label>Ideal Max Temperature</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Species__c/fields/Min_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Min_Temperature__c</fullName>
    <label>Ideal Min Temperature</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Species__c/fields/Summer_Watering_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Summer_Watering_Frequency__c</fullName>
    <label>Summer Watering Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Winter_Watering_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Winter_Watering_Frequency__c</fullName>
    <label>Winter Watering Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
  public Integer maxTemperature = 30;
  public Integer minTemperature = 0;

  public Id createSpecies() {
    Species__c species = new Species__c(
      Name = 'Species1',
      Summer_Watering_Frequency__c = 'Daily',
      Winter_Watering_Frequency__c = 'Weekly',
      Max_Temperature__c = maxTemperature,
      Min_Temperature__c = minTemperature
    );
    insert species;

    Plant__c plant1 = new Plant__c(
      Species__c = species.Id,
      Last_Watered__c = System.today(),
      Last_Fertilized__c = System.today()
    );
    insert plant1;

    Plant__c plant2 = new Plant__c(
      Species__c = species.Id,
      Last_Watered__c = System.today(),
      Last_Fertilized__c = System.today()
    );
    insert plant2;

    return species.Id;
  }
}