force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Acquisition_Date__c.field-meta.xml
<CustomField>
    <fullName>Acquisition_Date__c</fullName>
    <label>Acquisition Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Plants</relationshipLabel>
    <relationshipName>Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Species__c/Species__c.object-meta.xml
<CustomObject>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SpeciesServiceTest.cls
@isTest
private with sharing class SpeciesServiceTest {
  @isTest
  static void getFilteredSpecies_searchTextIsAnEmptyString() {
    // GIVEN
    Integer speciesCount = 6;
    List<Species__c> speciesToInsert = new List<Species__c>();
    for (Integer i = 0; i < speciesCount; i++) {
      Species__c species = new Species__c(Name = 'Species ' + i);
      speciesToInsert.add(species);
    }
    insert speciesToInsert;

    // WHEN
    List<Species__c> returnedSpecies = SpeciesService.getFilteredSpecies('');

    // THEN
    System.assertEquals(speciesCount, returnedSpecies.size());
  }

  @isTest
  static void getSpeciesWithPlants_returnsPlantsAndSpeciesCorrectly() {
    // GIVEN
    new TestDataFactory().createSpecies();

    // WHEN
    List<Species__c> returnedSpecies = SpeciesService.getSpeciesWithPlants();

    // THEN
    Assert.areEqual(1, returnedSpecies.size());
    Assert.areEqual(2, returnedSpecies[0].Plants__r.size());
  }

  @isTest
  static void createSpeciesWithPlant_createsSpeciesAndPlantCorrectly() {
    // GIVEN
    String speciesName = 'Species1';
    Date plantAcquisitionDate = System.today();

    // WHEN
    SpeciesService.createSpeciesWithPlant(speciesName, plantAcquisitionDate);

    // THEN
    List<Species__c> returnedSpecies = [SELECT Name FROM Species__c];
    List<Plant__c> returnedPlants = [SELECT Acquisition_Date__c FROM Plant__c];

    Assert.areEqual(1, returnedSpecies.size());
    Assert.areEqual(speciesName, returnedSpecies[0].Name);
    Assert.areEqual(1, returnedPlants.size());
    Assert.areEqual(
      plantAcquisitionDate,
      returnedPlants[0].Acquisition_Date__c
    );
  }
}