force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Plants</relationshipLabel>
    <relationshipName>Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant_with_Problem__e/Plant_with_Problem__e.object-meta.xml
<CustomObject>
    <label>Plant with Problem</label>
    <pluralLabel>Plans with Problems</pluralLabel>
</CustomObject>

force-app/main/default/objects/Plant_with_Problem__e/fields/Plant_Id__c.field-meta.xml
<CustomField>
    <fullName>Plant_Id__c</fullName>
    <label>Plant Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_with_Problem__e/fields/Tipo_de_Alerta__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Alerta__c</fullName>
    <description>Frio o calor</description>
    <label>Tipo de Alerta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Species__c/Species__c.object-meta.xml
<CustomObject>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Species__c/fields/Max_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Max_Temperature__c</fullName>
    <label>Ideal Max Temperature</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Species__c/fields/Min_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Min_Temperature__c</fullName>
    <label>Ideal Min Temperature</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ForecastService.cls
public inherited sharing class ForecastService {
  @future(callout=true)
  public static void postNotifications() {
    // Realizar las tares que queremos planificar
    // 1. Mirar que temperatura va a hacer hoy
    Forecast fc = ForecastService.getTodaysTemperatures();
    Integer maxTempToday = fc.temperaturas.max;
    Integer minTempToday = fc.temperaturas.min;

    // 2. Mirar si tengo alguna planta para la cual la tª no sea adecuada
    // Traerme las plantas cuya especie soporta temp max y min fuera del rango de la temp de hoy
    List<Plant__c> plantsWithProblems = [
      SELECT
        Name,
        Species__r.Name,
        Species__r.Max_Temperature__c,
        Species__r.Min_Temperature__c
      FROM Plant__c
      WHERE
        Species__c IN (
          SELECT Id
          FROM Species__c
          WHERE
            Max_Temperature__c < :maxTempToday
            OR Min_Temperature__c > :minTempToday
        )
      WITH SECURITY_ENFORCED
    ];

    // Get the Id for our custom notification type
    List<CustomNotificationType> notificationTypes = [
      SELECT Id, DeveloperName
      FROM CustomNotificationType
      WHERE DeveloperName = 'Temperature_Alert'
      WITH SECURITY_ENFORCED
    ];

    // 3. Si encuentro alguna, mandar notificación
    for (Plant__c plantWithProblems : plantsWithProblems) {
      // Only send notification if custom notification type is defined
      if (!notificationTypes.isEmpty()) {
        // Create a new custom notification
        Messaging.CustomNotification notification = new Messaging.CustomNotification();

        setNotificationMessage(
          notification,
          maxTempToday,
          minTempToday,
          plantWithProblems
        );

        // Set the notification type and target
        notification.setNotificationTypeId(notificationTypes[0].Id);
        notification.setTargetId(plantWithProblems.Id);

        // Actually send the notification
        CustomNotificationsService.send(notification);
      }

      // Send a platform event
      Plant_with_Problem__e plantWithProblemEvent = new Plant_with_Problem__e(
        Plant_Id__c = plantWithProblems.Id,
        Tipo_de_Alerta__c = getAlertType(
          maxTempToday,
          minTempToday,
          plantWithProblems
        )
      );

      List<Plant_with_Problem__e> plantWithProblemEvents = new List<Plant_with_Problem__e>();
      plantWithProblemEvents.add(plantWithProblemEvent);

      // Call method to publish events
      PlatformEventsService.publish(plantWithProblemEvents);
    }
  }

  private static void setNotificationMessage(
    Messaging.CustomNotification notification,
    Integer maxTempToday,
    Integer minTempToday,
    Plant__c plant
  ) {
    // Set the contents for the notification
    if (plant.Species__r.Max_Temperature__c < maxTempToday) {
      notification.setTitle('Mucho calor para tu planta!!!');
      notification.setBody(
        'Hoy el termómetro alcanzará ' +
          maxTempToday +
          ' grados.\n' +
          ' La temperatura máxima que ' +
          plant.Name +
          ' (' +
          plant.Species__r.Name +
          ') soporta es ' +
          plant.Species__r.Max_Temperature__c
      );
    } else if (plant.Species__r.Min_Temperature__c > minTempToday) {
      notification.setTitle('Mucho frío para tu planta!!!');
      notification.setBody(
        'Hoy el termómetro bajará de los ' +
          minTempToday +
          ' grados.\n' +
          ' La temperatura mínima que ' +
          plant.Name +
          ' (' +
          plant.Species__r.Name +
          ') soporta es ' +
          plant.Species__r.Max_Temperature__c
      );
    }
  }

  private static String getAlertType(
    Integer maxTempToday,
    Integer minTempToday,
    Plant__c plant
  ) {
    // Set the contents for the notification
    if (plant.Species__r.Max_Temperature__c < maxTempToday) {
      return 'calor';
    } else if (plant.Species__r.Min_Temperature__c > minTempToday) {
      return 'frio';
    }
    return 'error';
  }

  public static Forecast getTodaysTemperatures() {
    HttpRequest req = new HttpRequest();
    req.setEndpoint(
      'callout:El_tiempo/api/json/v2/provincias/18/municipios/18087'
    ); // Named credential
    req.setMethod('GET');

    Http http = new Http();
    HTTPResponse res = http.send(req);
    String body = res.getBody();

    Forecast forecast = (Forecast) JSON.deserialize(body, Forecast.class);
    return forecast;
  }

  public class Forecast {
    public Temperatures temperaturas;
  }

  public class Temperatures {
    public Integer max;
    public Integer min;
  }
}